source:
    build: .
    container_name: gpa_source
    command: /bin/true
    volumes:
        - .:/var/www
        - ~/.composer:/root/.composer
        - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro

nginx:
    build: ./docker/nginx
    container_name: gpa_nginx
    environment:
        PHP_FPM_HOST: php-fpm
        PHP_FPM_PORT: 9000
    ports:
        - 80:80
    links:
        - php-fpm:php-fpm
    volumes_from:
        - source

php-fpm:
    build: ./
    container_name: gpa
    volumes_from:
        - source
